[package]
name = "eleventy"
version = "0.1.0"
authors = ["Roman Gusev <rgusev2@gmail.com>"]
edition = "2018"
license = "MIT"
description = "An absolutely useless function that alway returns 110"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
